version: '3.8'
services:
  db:
    image: postgres:16
    container_name: ticketdeck_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/database/data/:/var/lib/postgresql/data
    networks:
      - ticketdeck.nl-network

  app:
    image: ticketdeck
    container_name: ticketdeck.nl-app
    depends_on:
      - db
    build:
      context: ./repository/ticketdeck/ticketdeck
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    networks:
      - ticketdeck.nl-network
      - reverse-proxy-main

networks:
  reverse-proxy-main:
    name: reverse-proxy-main
    external: true
  ticketdeck.nl-network:
    driver: bridge
